###########
# site.title

title:    'ICE CREAM'
subtitle: 'CS 175: Project in AI (in Minecraft) -- Minecraft Biome Landscape Image Completion'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
